name: Android CI

on:
  push:
    branches:
    - main
    - androidsupport
  pull_request:
    branches:
    - main
    - androidsupport

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build before
      run: ls -ll
    - name: Build GaiaXAndroidClientToStudio
      run: cd ./GaiaXAndroidClientToStudio && chmod +x ./gradlew && ./gradlew clean build -Pgroup=com.github.alibaba.GaiaX -Pversion=main-SNAPSHOT -xtest -xlint publishToMavenLocal
    - name: Build GaiaXAnalyze
      run: cd ./GaiaXAnalyze/GXAnalyzeAndroid && chmod +x ./gradlew && ./gradlew clean build -Pgroup=com.github.alibaba.GaiaX -Pversion=main-SNAPSHOT -xtest -xlint publishToMavenLocal
    - name: Build GaiaXAndroid 
      run: cd ./GaiaXAndroid && chmod +x ./gradlew && ./gradlew clean build -Pgroup=com.github.alibaba.GaiaX -Pversion=main-SNAPSHOT -xtest -xlint publishToMavenLocal
    - name: Build GaiaXAndroidAdapter 
      run: cd ./GaiaXAndroidAdapter && chmod +x ./gradlew && ./gradlew clean build -Pgroup=com.github.alibaba.GaiaX -Pversion=main-SNAPSHOT -xtest -xlint publishToMavenLocal